import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import StoreProvider from "./StoreProvider";
import RequireAuth from "./authAtatus";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <RequireAuth>
            {" "}
            <Header />
            {children}
            <Footer />
          </RequireAuth>
        </StoreProvider>
      </body>
    </html>
  );
}
